const meds=[
['Norepinephrine','Vasopressor','First-line vasopressor in distributive shock. Predominantly alpha effect; titrate per ordered MAP target.','MAP, rhythm, perfusion, lactate, urine output','Extravasation; rising dose warrants reassessment of source control, volume status, cardiac function, acidemia.'],
['Vasopressin','Vasopressor','Non-catecholamine adjunct commonly used in vasodilatory shock. Often ordered at a fixed dose.','MAP, perfusion, sodium, ischemic signs','Follow local protocol for dose and central/peripheral administration.'],
['Epinephrine','Vasopressor / inotrope','Increases inotropy, chronotropy, and vasoconstriction; used for refractory shock, anaphylaxis, and ACLS.','MAP, rhythm, lactate, glucose, potassium','Can raise lactate through beta-adrenergic effect; interpret clinical context.'],
['Phenylephrine','Vasopressor','Predominantly alpha agonist; increases SVR with minimal direct beta effect.','MAP, HR, perfusion','May reduce stroke volume in some patients; evaluate cause of hypotension.'],
['Dobutamine','Inotrope','Beta-agonist inotrope for low cardiac output states when blood pressure allows.','HR/rhythm, BP, perfusion, urine output','Can cause hypotension and tachyarrhythmias.'],
['Amiodarone','Antiarrhythmic','Used for ventricular arrhythmias and selected atrial tachyarrhythmias per order.','Rhythm, QTc, BP, liver function','IV administration can cause hypotension; verify line/filter and compatibility policy.'],
['Diltiazem','Rate control','Calcium channel blocker for selected supraventricular tachyarrhythmias.','HR, BP, rhythm','Use caution with hypotension or reduced systolic function; follow provider order.'],
['Propofol','Sedative','Short-acting sedative commonly used for mechanically ventilated patients.','RASS, BP, triglycerides, calories, respiratory status','Hypotension and hypertriglyceridemia; track lipid calories and local monitoring practice.'],
['Dexmedetomidine','Sedative','Alpha-2 sedative; may support lighter, arousable sedation.','RASS, HR, BP','Bradycardia and hypotension are common concerns.'],
['Fentanyl','Analgesic','Opioid analgesia for pain and ventilator synchrony as ordered.','Pain scale, RR, BP, bowel function','Accumulation/withdrawal considerations; assess sedation separately when possible.'],
['Midazolam','Sedative','Benzodiazepine sedation for selected patients, seizures, or procedures.','RASS, respiratory status, BP','May accumulate, especially with prolonged infusion or organ dysfunction.'],
['Ketamine','Analgesic / sedative','Dissociative agent used for procedures, induction, or adjunct analgesia/sedation.','BP, HR, mental status, secretions','Can increase secretions; emergence reactions possible.'],
['Heparin','Anticoagulant','Anticoagulation infusion or prophylaxis per indication and protocol.','aPTT/anti-Xa, platelets, bleeding signs','Use institution nomogram; consider HIT when platelets fall in the appropriate context.'],
['Insulin','Metabolic','IV infusion for hyperglycemia, DKA/HHS, or hyperkalemia per protocol.','Glucose frequency, potassium, anion gap when applicable','Never pause monitoring; hypoglycemia and hypokalemia are major risks.'],
['Sodium bicarbonate','Buffer','May be used in specific severe acid-base or toxicologic scenarios; treats numbers less than underlying cause.','pH/PaCO2, sodium, potassium, calcium, volume status','Produces CO2; adequate ventilation matters. Verify indication and local practice.']];
const dx=[
['Septic shock','Shock','Suspected infection with vasodilation and impaired perfusion.','MAP, lactate trend, UOP, mentation, cultures, antibiotic timing','Think source control, volume status, cardiac function, and peripheral perfusion—not MAP alone.'],
['Cardiogenic shock','Shock','Low cardiac output causing tissue hypoperfusion, often with congestion.','MAP, rhythm, UOP, lactate, extremities, lung exam','Watch carefully for pulmonary edema and dysrhythmia; hemodynamic plan is individualized.'],
['Hypovolemic shock','Shock','Inadequate circulating volume from hemorrhage or fluid loss.','HR, MAP, Hgb/bleeding, UOP, mentation','Find and control the loss; reassess response to ordered resuscitation.'],
['Obstructive shock','Shock','Mechanical impairment of cardiac filling or output (e.g., PE, tamponade, tension physiology).','Sudden change, JVD, lung sounds, bedside ultrasound if available','Escalate early; definitive treatment is cause-specific.'],
['ARDS','Respiratory','Inflammatory noncardiogenic pulmonary edema with impaired oxygenation.','SpO2/ABG, P/F ratio, plateau pressure, ventilator synchrony','Lung-protective ventilation and proning decisions are team/protocol driven.'],
['COPD exacerbation','Respiratory','Airflow obstruction with dynamic hyperinflation risk.','Work of breathing, ABG, auto-PEEP, mental status','Allow adequate exhalation; rising pressures can be air trapping.'],
['Pulmonary edema','Respiratory','Fluid in alveoli from cardiogenic or noncardiogenic causes.','Oxygenation, work of breathing, BP, I&O, lung exam','Rapid changes require re-evaluation of cause and ventilation plan.'],
['Pulmonary embolism','Respiratory','Pulmonary vascular obstruction that can strain the right ventricle.','O2 need, HR, BP, signs of RV strain, bleeding risk','Sudden hypotension or syncope signals high risk—escalate promptly.'],
['Acute kidney injury','Renal','Abrupt decline in renal function from perfusion, injury, or obstruction.','UOP, creatinine, potassium, bicarbonate, volume status','Trend rather than a single creatinine; review nephrotoxins and obstruction clues.'],
['DKA / HHS','Endocrine','Hyperglycemic crisis with dehydration; DKA includes ketoacidosis.','Glucose, potassium, anion gap, bicarbonate, neuro status','Use institutional insulin/fluid/electrolyte protocol; potassium drives safety.'],
['GI bleeding','Hematology','Overt or occult blood loss from GI tract.','Hemodynamics, Hgb trend, stool/emesis, coags, access','Massive bleeding is a resuscitation and source-control problem; follow transfusion policy.'],
['DIC','Hematology','Consumptive coagulopathy secondary to an underlying trigger.','Platelets, fibrinogen, PT/INR, bleeding/thrombosis','Treat the trigger; component support follows provider/institutional plan.'],
['Status epilepticus','Neuro','Prolonged or recurrent seizure activity without recovery.','Airway, glucose, temperature, seizure timing, EEG if ordered','Time and document events precisely; airway and medication sequence are protocol-driven.'],
['Increased ICP','Neuro','Elevated intracranial pressure risks reduced cerebral perfusion.','Neuro checks, pupils, BP/MAP, sodium/osmolality if ordered','Avoid delays in new neuro changes; positioning and osmotherapy follow local orders.'],
['Post-cardiac arrest syndrome','Cardiac','Global ischemia-reperfusion injury after ROSC.','Airway/O2/CO2, MAP, rhythm, temperature, glucose, neuro exam','Avoid hyperoxia/hypotension; follow your post-ROSC pathway.']];
const quick=[
['MAP <65 / refractory hypotension','Confirm measurement and rhythm; assess perfusion, volume status, bleeding, sepsis/source control, pump failure, obstruction, and medication effects. Trend lactate/UOP/mentation; escalate early.','Call/escalate for worsening perfusion, rapidly increasing pressor needs, new dysrhythmia, suspected hemorrhage, or concern for obstruction.'],
['Severe metabolic acidosis','Confirm ABG/VBG and chemistry; calculate anion gap; assess lactate, ketones, renal failure, toxins, diarrhea/renal losses. Assess ventilation—bicarbonate can increase CO2 burden.','Escalate severe acidemia, rising lactate, hyperkalemia, declining mental status, or ventilation failure.'],
['Refractory hypoxemia','Check patient first: airway, chest rise, waveform, secretions, tube depth, breath sounds, hemodynamics. Then circuit/ventilator: FiO2 source, disconnection, pressures, PEEP, alarms. Consider edema, ARDS, PE, pneumothorax.','Call immediately for rapidly falling SpO2, unilateral absent sounds, severe distress, instability, or suspected tension physiology.'],
['Post-ROSC','Prioritize airway/ventilation, avoid hypoxemia and hyperoxia, support ordered MAP target, obtain 12-lead/labs, temperature management, and frequent neurologic assessment.','Activate your facility post-arrest pathway; document timing and interventions.'],
['Sudden ventilator deterioration','Use DOPE: Displacement, Obstruction, Pneumothorax, Equipment. Disconnect and bag per emergency protocol if indicated; assess patient and call for help.','A sudden pressure, volume, or oxygenation change is an emergency until assessed.']];
// Batch 2: educational summaries only. Follow current orders, pump library, pharmacy, and local policy.
const enrich=(name,detail,source)=>{let x=meds.find(x=>x[0]===name);if(x){x[5]=detail;x[6]=source}};
enrich('Ketamine','Common examples: RSI 1-2 mg/kg IV; analgesia 0.1-0.3 mg/kg IV slowly or 0.1-0.4 mg/kg/hr. ICU-sedation range is protocol-dependent. Titrate to ordered pain/RASS and reassess BP, HR, respiratory status, SpO2, ETCO2 when available, secretions, and mental status. Stop/escalate for apnea, respiratory depression, severe hypertension/tachyarrhythmia, laryngospasm, or unsafe airway.','DailyMed ketamine label; multi-society consensus');
enrich('Heparin','Common VTE example: 80 units/kg IV bolus then 18 units/kg/hr; lower-intensity starts are indication-specific. A common concentration is 25,000 units/250 mL (100 units/mL). Titrate only with the active anti-Xa/aPTT nomogram. Stop/notify for active bleeding, critical result, suspected HIT, new thrombosis, or major platelet fall.','UW Medicine protocols; practical heparin guidance');
enrich('Amiodarone','For recurrent VF/unstable VT: 150 mg in 100 mL D5W over 10 min, then 1 mg/min for 6 hr, then 0.5 mg/min. AF with RVR needs indication-specific orders. Use continuous ECG/BP, track QTc and K/Mg, and slow/stop for hypotension, bradycardia, AV block, QT prolongation, or site injury.','DailyMed amiodarone IV label');
meds.push(
['Rocuronium / succinylcholine','RSI paralysis','Neuromuscular blockade for RSI; neither provides analgesia, amnesia, or sedation.','Induction before paralysis, airway/ventilation readiness, post-intubation analgesia/sedation, TOF if ongoing blockade','Confirm unconsciousness and immediate oxygenation/ventilation capability before administration.','Rocuronium RSI: 0.6-1.2 mg/kg IV. Succinylcholine adult label average: 0.6 mg/kg IV; local RSI protocols vary. Single RSI doses are not titrated. Avoid succinylcholine after acute burns, crush trauma, denervation, upper motor-neuron injury, or myopathy because of hyperkalemia risk; assess malignant-hyperthermia, bradycardia, and prolonged-apnea risk.','DailyMed rocuronium and succinylcholine labels'],
['Nicardipine','Antihypertensive infusion','Short-term severe hypertension control when oral therapy is not feasible; syndrome-specific targets apply.','Continuous BP/HR, ordered SBP/MAP goal, perfusion, infusion site','Avoid precipitous BP reduction; stop for unacceptable hypotension/tachycardia.','Label: start 5 mg/hr; increase 2.5 mg/hr every 5 min (rapid) or 15 min (gradual); max 15 mg/hr. Common premixes are 0.1 or 0.2 mg/mL. Contraindicated in advanced aortic stenosis. Watch for hypotension, reflex tachycardia, angina/HF worsening, and site injury.','DailyMed Cardene IV label'],
['Nitroglycerin','Vasodilator infusion','Acute coronary ischemia, cardiogenic pulmonary edema, and selected hypertensive emergencies when preload/BP permit.','Continuous BP/HR, chest pain, work of breathing, pulmonary edema, hemodynamics','Stop/escalate for hypotension, syncope, worsening ischemia, or marked rate change.','Label: start 5 mcg/min with non-adsorptive tubing; increase 5 mcg/min every 3-5 min initially. Common premix: 50 mg/250 mL (200 mcg/mL). Avoid preload-dependent states and recent PDE-5 inhibitor or riociguat exposure. Confirm tubing/filter policy.','DailyMed nitroglycerin IV label'],
['Furosemide infusion','Loop diuretic infusion','Controlled diuresis for acute pulmonary edema/volume overload; regimen is protocol-dependent.','Strict I/O, urine output, weight, BP, creatinine/BUN, Na/K/Mg/bicarbonate, hearing symptoms','Stop/escalate for severe hypotension, worsening oliguria/azotemia, electrolyte loss, or hearing change.','A common adult approach is a loading dose then 5-20 mg/hr, individualized for renal function and prior exposure. A common concentration is 1 mg/mL. Titrate to ordered urine-output/net-balance goal. Contraindicated in anuria; adult IV infusion should not exceed 4 mg/min.','DailyMed furosemide injection label'],
['Magnesium sulfate','Electrolyte / antiarrhythmic','Hypomagnesemia replacement; torsades/polymorphic VT with prolonged QT.','Magnesium, potassium/calcium as indicated, renal function/UOP, ECG with unstable arrhythmia','Stop/escalate for hyporeflexia, respiratory decline, major hypotension/bradycardia, or conduction block.','For torsades with a pulse, a common emergency dose is 1-2 g IV diluted over about 5-15 min; repeat only per ACLS/local protocol. Replacement thresholds are protocol-dependent. Reduce repeated empiric dosing in renal impairment. Verify grams versus milligrams and concentration.','Electrolyte-replacement and EMS protocols']
);
dx.push(
['Hyperkalemia','Electrolyte emergency','Severe potassium elevation can cause lethal conduction disturbance even with an initially normal ECG.','Repeat potassium, rhythm/12-lead ECG, glucose after insulin, renal function, acid-base status','ECG changes, K >6.5, rapid rise, weakness, oligo-anuria, acidosis, or poor response require urgent escalation.','Immediate approach: cardiac monitoring, ECG, repeat potassium. IV calcium stabilizes myocardium with ECG changes/instability but does not lower K. Shift K with insulin/dextrose and albuterol per order; remove K with appropriate diuresis, binder, or dialysis. Recheck K and glucose for delayed hypoglycemia.','ACEP adult hyperkalemia algorithm'],
['Hyponatremia','Electrolyte emergency','Severity and onset matter: assess headache, nausea, confusion, seizures, coma, and respiratory compromise.','Frequent sodium and neurologic checks; glucose, osmolality, urine output, urine studies as ordered','Seizure, coma, deterioration, respiratory failure, acute water intoxication, or overcorrection require urgent escalation.','For severe symptoms, a common US regimen is 3% saline 100 mL IV over 10 min, repeat up to twice if symptoms persist; local order set controls. Initial goal is about 4-6 mmol/L rise, not normalization. Avoid correction >8 mmol/L/24 hr in high-risk patients.','US/European guideline comparison'],
['Hypertensive emergency','Cardiovascular emergency','Severe BP elevation plus acute target-organ injury; the BP number alone is not an emergency.','Confirmed BP technique, neuro/cardiac/renal/perfusion status, diagnosis-specific target','Suspected dissection, stroke/ICH, ACS/pulmonary edema, eclampsia, or catecholamine crisis needs syndrome-specific treatment.','Screen brain, arteries, retina, kidneys, and heart. Use a monitored, titratable IV agent appropriate to the syndrome. General guidance is no more than about 20-25% SBP/MAP reduction in the first hour, then toward roughly 160/100 over 2-6 hr if stable.','AHA acute-care BP scientific statement'],
['Alcohol withdrawal / CIWA-Ar','Withdrawal','CIWA-Ar is unreliable for intubated, deeply sedated, delirious, or noncommunicative patients.','Last drink, prior seizures/DTs, vitals, orientation, autonomic signs, glucose/electrolytes, airway/ventilation','Seizure, DTs, unsafe agitation, autonomic instability, hyperthermia, rising sedative need, or respiratory depression need escalation.','Use the local symptom-triggered/front-loading/fixed-dose pathway; benzodiazepines are first-line. If CIWA-Ar is invalid, use the ICU RASS/MINDS pathway. Give thiamine as ordered and correct fluids/electrolytes. Alpha-2 agonists/beta-blockers may mask signs and do not treat withdrawal.','ASAM alcohol withdrawal guideline'],
['Delirium / CAM-ICU','Neuro / ICU assessment','Assess arousal before CAM-ICU: RASS -4/-5 is coma and not assessable.','RASS, CAM-ICU trend, baseline cognition, oxygenation/ventilation, infection, glucose, medication review','New focal deficit, seizure, falling consciousness, severe gas-exchange issue, hypoglycemia, sepsis, or unsafe agitation needs evaluation.','CAM-ICU positive: acute/fluctuating course plus inattention, plus altered LOC or disorganized thinking. Treat the driver and apply ABCDEF: pain, SAT/SBT coordination, appropriate sedation, delirium checks, early mobility, and family engagement.','SCCM ICU Liberation Bundle'],
['ABG interpreter','Bedside tool','Use a consistent sequence: pH, primary process, expected compensation, anion gap/albumin, mixed disorder, clinical cause.','pH, PaCO2, HCO3, chemistry HCO3 when available, Na/Cl/albumin, lactate/ketones as indicated','Compensation outside expected range or high-gap mismatch suggests mixed disease.','Metabolic acidosis expected PaCO2 = 1.5 x HCO3 + 8 +/-2. Metabolic alkalosis expected PaCO2 about 0.7 x (HCO3-24)+40 +/-2. AG = Na-(Cl+HCO3); albumin-corrected AG about measured AG+2.5 x (4-albumin g/dL).','Merck Manual acid-base disorders'],
['Oxygen-delivery devices','Bedside tool','FiO2 is estimated unless a device delivers a fixed concentration; fit, minute ventilation, and equipment matter.','Ordered SpO2 target, work of breathing, RR, mental status, oxygenation, hypercapnia/acidosis','Rising O2 need, persistent hypoxemia, exhaustion, worsening hypercapnia/acidosis, or declining mental status requires early airway escalation.','Nasal cannula 1-6 L/min about 24-44%. Simple mask 6-10 L/min about 35-50%: never below 6. Nonrebreather 10-15 L/min about 60-80%: keep reservoir inflated. Venturi 24-60% adapter-specific. HFNC up to 60 L/min. CPAP one pressure; BiPAP IPAP/EPAP. NIV is unsafe/failing with inability to protect airway, vomiting, secretions, major instability, or no improvement.','Open RN oxygenation equipment']
);
const $=s=>document.querySelector(s), app=$('#app');let tab='home',query='',detail=null;let fav=JSON.parse(localStorage.favs||'[]');const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function header(){return `<header class="top"><div class="brand"><div class="mark">+</div><div><div class="eyebrow">Personal bedside brain</div><div class="title">ICU Pocket Reference</div></div></div><button class="back" onclick="show('favorites')">★ ${fav.length}</button></header>`}function cards(){return `<div class="grid"><button class="card" onclick="show('meds')"><div class="icon">💊</div><strong>Medications</strong><small>${meds.length} quick cards</small></button><button class="card" onclick="show('dx')"><div class="icon">▣</div><strong>Conditions</strong><small>${dx.length} ICU essentials</small></button><button class="card" onclick="show('quick')"><div class="icon">⚡</div><strong>Right now</strong><small>Problem guides</small></button><button class="card" onclick="show('calcs')"><div class="icon">⌁</div><strong>Calculators</strong><small>7 bedside tools</small></button><button class="card" onclick="show('notes')"><div class="icon">✎</div><strong>My protocols</strong><small>Private local notes</small></button></div>`}
function list(items,type){let filtered=items.filter(x=>x.join(' ').toLowerCase().includes(query.toLowerCase()));return `<h2>${type==='med'?'Medications':'Conditions'}</h2><div class="count">${filtered.length} result${filtered.length===1?'':'s'}</div><div class="list">${filtered.map((x,i)=>`<button class="item" onclick="openDetail('${type}',${items.indexOf(x)})"><span class="tag">${esc(x[1])}</span><h3>${esc(x[0])}</h3><small>${esc(x[2])}</small>${fav.includes(type+items.indexOf(x))?'<span class="star">★</span>':''}</button>`).join('')||'<div class="empty">No matching reference found.</div>'}</div>`}
function detailView(type,i){let x=(type==='med'?meds:dx)[i],id=type+i,star=fav.includes(id),detail=x[5]?`<div class="section"><h3>Batch 2 bedside card</h3><p>${esc(x[5]).replace(/\n/g,'<br>')}</p>${x[6]?`<small>Source: ${esc(x[6])}</small>`:''}</div>`:'';return `<button class="back" onclick="show('${type==='med'?'meds':'dx'}')">← Back</button><article class="detail"><div class="detail-head"><div><h1>${esc(x[0])}</h1><div class="tag">${esc(x[1])} · general education</div></div><button class="star" onclick="toggleFav('${id}')">${star?'★':'☆'}</button></div><div class="section"><h3>Overview</h3><p>${esc(x[2])}</p></div><div class="section"><h3>Monitor / trend</h3><p>${esc(x[3])}</p></div><div class="section warn"><h3>ICU pearl</h3><p>${esc(x[4])}</p></div>${detail}${noteBox(id,x[0])}</article>`}
function noteBox(id,name){return `<div class="protocol"><label>MY WORKPLACE NOTES — PRIVATE / LOCAL ONLY</label><small>Not a hospital policy. Verify against your current orders, policies, and pharmacy guidance.</small><textarea id="note">${esc(localStorage['note-'+id]||'')}</textarea><button class="save" onclick="saveNote('${id}')">Save notes for ${esc(name)}</button></div>`}
function quickView(){return `<h2>Right now</h2><p class="count">General reference only — use emergency response systems and local protocols.</p><div class="list">${quick.map((x,i)=>`<button class="item" onclick="openDetail('quick',${i})"><span class="tag">Problem guide</span><h3>${x[0]}</h3><small>${x[1]}</small></button>`).join('')}</div>`}function quickDetail(i){let x=quick[i];return `<button class="back" onclick="show('quick')">← Back</button><article class="detail"><h1>${x[0]}</h1><div class="section danger"><h3>Rapid bedside check</h3><p>${x[1]}</p></div><div class="section warn"><h3>Communicate / escalate</h3><p>${x[2]}</p></div>${noteBox('quick'+i,x[0])}</article>`}
const calc=[['MAP','(SBP + 2 × DBP) ÷ 3',[['SBP','sbp'],['DBP','dbp']],v=>((v.sbp+2*v.dbp)/3).toFixed(0)+' mmHg'],['Anion gap','Na − (Cl + HCO₃)',[['Na','na'],['Cl','cl'],['HCO₃','hco3']],v=>(v.na-v.cl-v.hco3).toFixed(1)+' mEq/L'],['Corrected sodium','Na + 1.6 × ((glucose − 100) ÷ 100)',[['Na','na'],['Glucose','glu']],v=>(v.na+1.6*((v.glu-100)/100)).toFixed(1)+' mEq/L'],['Corrected calcium','Ca + 0.8 × (4 − albumin)',[['Calcium','ca'],['Albumin','alb']],v=>(v.ca+.8*(4-v.alb)).toFixed(2)+' mg/dL'],['P/F ratio','PaO₂ ÷ FiO₂ (decimal)',[['PaO₂','pao2'],['FiO₂ %','fio2']],v=>(v.pao2/(v.fio2/100)).toFixed(0)],['QTc (Bazett)','QT ÷ √RR (both in seconds)',[['QT ms','qt'],['HR bpm','hr']],v=>{let rr=60/v.hr;return (v.qt/1000/Math.sqrt(rr)*1000).toFixed(0)+' ms'}],['Shock index','HR ÷ SBP',[['HR','hr'],['SBP','sbp']],v=>(v.hr/v.sbp).toFixed(2)]];
function calcs(){return `<h2>Calculators</h2><p class="count">Check units and interpret with the full clinical picture.</p>${calc.map((c,i)=>`<div class="calc"><h3>${c[0]}</h3><small>${c[1]}</small><div class="fields">${c[2].map(f=>`<label>${f[0]}<input type="number" inputmode="decimal" id="c${i}-${f[1]}" oninput="runCalc(${i})"></label>`).join('')}</div><div class="result" id="r${i}">—</div></div>`).join('')}`}
function notes(){return `<h2>My protocols & notes</h2><div class="protocol"><label>PRIVATE WORKPLACE REFERENCE</label><p>Keep hospital-specific policies, phone numbers, dilution notes, and workflow reminders here. This stays in this browser on this device.</p><textarea id="master-note" placeholder="Example: Sepsis pathway location, rapid response extension, unit-specific titration reminder…">${esc(localStorage.masterNotes||'')}</textarea><button class="save" onclick="localStorage.masterNotes=$('#master-note').value;alert('Saved on this device.')">Save my notes</button></div><div class="section warn"><h3>Safety boundary</h3><p>This app is a personal educational reference, not a prescribing tool or replacement for clinical judgment, orders, current institutional policy, pharmacy guidance, or emergency response procedures.</p></div>`}
function render(){let body=detail?(detail.type==='quick'?quickDetail(detail.i):detailView(detail.type,detail.i)):tab==='home'?`<div class="disclaimer"><strong>General education only.</strong> Use current orders, institution policies, pharmacy guidance, and clinical judgment.</div><div class="search">⌕ <input autofocus placeholder="Search meds, conditions, problems…" value="${esc(query)}" oninput="query=this.value;searchAll()"></div>${query?searchResults():`<h2>Quick access</h2><div class="quick">${quick.slice(0,3).map((x,i)=>`<button class="card" onclick="openDetail('quick',${i})"><div class="tag">Right now</div><strong>${x[0]}</strong></button>`).join('')}</div><h2>Browse</h2>${cards()}`}`:tab==='meds'?list(meds,'med'):tab==='dx'?list(dx,'dx'):tab==='quick'?quickView():tab==='calcs'?calcs():tab==='notes'?notes():favorites();app.innerHTML=header()+body+`<nav class="nav"><div class="nav-inner">${[['home','⌂','Home'],['meds','💊','Meds'],['dx','▣','Conditions'],['calcs','⌁','Tools'],['notes','✎','Notes']].map(n=>`<button class="${tab===n[0]&&!detail?'active':''}" onclick="show('${n[0]}')"><span>${n[1]}</span>${n[2]}</button>`).join('')}</div></nav>`}
function searchResults(){let all=[...meds.map((x,i)=>['med',i,x]),...dx.map((x,i)=>['dx',i,x]),...quick.map((x,i)=>['quick',i,x])].filter(x=>x[2].join(' ').toLowerCase().includes(query.toLowerCase()));return `<h2>Search</h2><div class="list">${all.map(x=>`<button class="item" onclick="openDetail('${x[0]}',${x[1]})"><span class="tag">${x[0]==='med'?'Medication':x[0]==='dx'?'Condition':'Problem guide'}</span><h3>${x[2][0]}</h3><small>${x[2][2]}</small></button>`).join('')||'<div class="empty">No matches.</div>'}</div>`}function favorites(){let all=[...meds.map((x,i)=>['med',i,x]),...dx.map((x,i)=>['dx',i,x])].filter(x=>fav.includes(x[0]+x[1]));return `<h2>Favorites</h2><div class="list">${all.map(x=>`<button class="item" onclick="openDetail('${x[0]}',${x[1]})"><span class="tag">${x[2][1]}</span><h3>${x[2][0]}</h3></button>`).join('')||'<div class="empty">Tap ☆ on any medication or condition to keep it here.</div>'}</div>`}function show(x){tab=x;detail=null;query='';render();scrollTo(0,0)}function openDetail(type,i){detail={type,i};render();scrollTo(0,0)}function toggleFav(id){fav=fav.includes(id)?fav.filter(x=>x!==id):[...fav,id];localStorage.favs=JSON.stringify(fav);render()}function saveNote(id){localStorage['note-'+id]=$('#note').value;alert('Saved on this device.')}function runCalc(i){let c=calc[i],v={};c[2].forEach(f=>v[f[1]]=Number($('#c'+i+'-'+f[1]).value));$('#r'+i).textContent=c[2].every(f=>Number.isFinite(v[f[1]])&&v[f[1]]!==0)?c[3](v):'—'}function searchAll(){render()}if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
const refs=[
['Sepsis & septic shock','Surviving Sepsis Campaign, 2021','https://www.idsociety.org/practice-guideline/surviving-sepsis-campaign-adult-guidelines-2021','Primary guideline for septic-shock content and vasopressor framing.'],
['Cardiac arrest / post-ROSC','American Heart Association: Adult Advanced Life Support','https://cpr.heart.org/en/resuscitation-science/cpr-and-ecc-guidelines/adult-advanced-life-support/','Current AHA guideline hub for adult cardiac arrest and cardiovascular emergencies.'],
['Sedation, analgesia & delirium','SCCM PADIS Guidelines','https://www.sccm.org/clinical-resources/guidelines/guidelines/guidelines-for-the-prevention-and-management-of-pa','Source for general ICU sedation and analgesia concepts.'],
['Acute kidney injury','KDIGO AKI / AKD Guideline hub','https://kdigo.org/guidelines/acute-kidney-injury/','Check current publication status and your local pathway.'],
['Medication details','FDA Drugs@FDA','https://www.accessdata.fda.gov/scripts/cder/daf/','Use current labeling, pharmacy guidance, and local policy for doses and administration.']];
function references(){return `<h2>References</h2><p class="count">Starter sources for this educational build. Check the current guideline and follow local policy where it differs.</p><div class="list">${refs.map(r=>`<a class="item" style="color:var(--text);text-decoration:none" href="${r[2]}" target="_blank" rel="noopener"><span class="tag">${r[0]}</span><h3>${r[1]} ↗</h3><small>${r[3]}</small></a>`).join('')}</div><div class="section warn"><h3>Source scope</h3><p>These sources support the general topics; bedside summaries are not line-by-line evidence mapped. Medication doses, dilutions, compatibility, and titration are intentionally omitted: use your pharmacy and institutional references.</p></div>`}
cards=()=>`<div class="grid"><button class="card" onclick="show('meds')"><div class="icon">M</div><strong>Medications</strong><small>${meds.length} quick cards</small></button><button class="card" onclick="show('dx')"><div class="icon">+</div><strong>Conditions</strong><small>${dx.length} ICU essentials</small></button><button class="card" onclick="show('quick')"><div class="icon">!</div><strong>Right now</strong><small>Problem guides</small></button><button class="card" onclick="show('calcs')"><div class="icon">#</div><strong>Calculators</strong><small>7 bedside tools</small></button><button class="card" onclick="show('notes')"><div class="icon">N</div><strong>My protocols</strong><small>Private local notes</small></button><button class="card" onclick="show('refs')"><div class="icon">R</div><strong>References</strong><small>Guidelines & sources</small></button></div>`;
render=function(){let body=detail?(detail.type==='quick'?quickDetail(detail.i):detailView(detail.type,detail.i)):tab==='home'?`<div class="disclaimer"><strong>General education only.</strong> Use current orders, institution policies, pharmacy guidance, and clinical judgment.</div><div class="search">Search <input autofocus placeholder="Search meds, conditions, problems..." value="${esc(query)}" oninput="query=this.value;searchAll()"></div>${query?searchResults():`<h2>Quick access</h2><div class="quick">${quick.slice(0,3).map((x,i)=>`<button class="card" onclick="openDetail('quick',${i})"><div class="tag">Right now</div><strong>${x[0]}</strong></button>`).join('')}</div><h2>Browse</h2>${cards()}`}`:tab==='meds'?list(meds,'med'):tab==='dx'?list(dx,'dx'):tab==='quick'?quickView():tab==='calcs'?calcs():tab==='notes'?notes():tab==='refs'?references():favorites();app.innerHTML=header()+body+`<nav class="nav"><div class="nav-inner">${[['home','Home'],['meds','Meds'],['dx','Conditions'],['calcs','Tools'],['notes','Notes']].map(n=>`<button class="${tab===n[0]&&!detail?'active':''}" onclick="show('${n[0]}')">${n[1]}</button>`).join('')}</div></nav>`};render();
