const meds=[
['Norepinephrine','Vasopressor','First-line vasopressor in distributive shock. Predominantly alpha effect; titrate per ordered MAP target.','MAP, rhythm, perfusion, lactate, urine output','Extravasation; rising dose warrants reassessment of source control, volume status, cardiac function, acidemia.'],
['Vasopressin','Vasopressor','Non-catecholamine adjunct commonly used in vasodilatory shock. Often ordered at a fixed dose.','MAP, perfusion, sodium, ischemic signs','Follow local protocol for dose and central/peripheral administration.'],
['Epinephrine','Vasopressor / inotrope','Increases inotropy, chronotropy, and vasoconstriction; used for refractory shock, anaphylaxis, and ACLS.','MAP, rhythm, lactate, glucose, potassium','Can raise lactate through beta-adrenergic effect; interpret clinical context.'],
['Phenylephrine','Vasopressor','Predominantly alpha agonist; increases SVR with minimal direct beta effect.','MAP, HR, perfusion','May reduce stroke volume in some patients; evaluate cause of hypotension.'],
['Dobutamine','Inotrope','Beta-agonist inotrope for low cardiac output states when blood pressure allows.','HR/rhythm, BP, perfusion, urine output','Can cause hypotension and tachyarrhythmias.'],
['Amiodarone','Antiarrhythmic','Used for ventricular arrhythmias and selected atrial tachyarrhythmias per order.','Rhythm, QTc, BP, liver function','IV administration can cause hypotension; verify line/filter and compatibility policy.'],
['Diltiazem','Rate control','Calcium channel blocker for selected supraventricular tachyarrhythmias.','HR, BP, rhythm','Use caution with hypotension or reduced systolic function; follow provider order.'],
['Propofol','Sedative','Short-acting sedative commonly used for mechanically ventilated patients.','RASS, BP, triglycerides, calories, respiratory status','Hypotension and hypertriglyceridemia; track lipid calories and local monitoring practice.'],
['Dexmedetomidine','Sedative','Alpha-2 sedative; may support lighter, arousable sedation.','RASS, HR, BP','Bradycardia and hypotension are common concerns.'],
['Fentanyl','Analgesic','Opioid analgesia for pain and ventilator synchrony as ordered.','Pain scale, RR, BP, bowel function','Accumulation/withdrawal considerations; assess sedation separately when possible.'],
['Midazolam','Sedative','Benzodiazepine sedation for selected patients, seizures, or procedures.','RASS, respiratory status, BP','May accumulate, especially with prolonged infusion or organ dysfunction.'],
['Ketamine','Analgesic / sedative','Dissociative agent used for procedures, induction, or adjunct analgesia/sedation.','BP, HR, mental status, secretions','Can increase secretions; emergence reactions possible.'],
['Heparin','Anticoagulant','Anticoagulation infusion or prophylaxis per indication and protocol.','aPTT/anti-Xa, platelets, bleeding signs','Use institution nomogram; consider HIT when platelets fall in the appropriate context.'],
['Insulin','Metabolic','IV infusion for hyperglycemia, DKA/HHS, or hyperkalemia per protocol.','Glucose frequency, potassium, anion gap when applicable','Never pause monitoring; hypoglycemia and hypokalemia are major risks.'],
['Sodium bicarbonate','Buffer','May be used in specific severe acid-base or toxicologic scenarios; treats numbers less than underlying cause.','pH/PaCO2, sodium, potassium, calcium, volume status','Produces CO2; adequate ventilation matters. Verify indication and local practice.']];
const dx=[
['Septic shock','Shock','Suspected infection with vasodilation and impaired perfusion.','MAP, lactate trend, UOP, mentation, cultures, antibiotic timing','Think source control, volume status, cardiac function, and peripheral perfusion—not MAP alone.'],
['Cardiogenic shock','Shock','Low cardiac output causing tissue hypoperfusion, often with congestion.','MAP, rhythm, UOP, lactate, extremities, lung exam','Watch carefully for pulmonary edema and dysrhythmia; hemodynamic plan is individualized.'],
['Hypovolemic shock','Shock','Inadequate circulating volume from hemorrhage or fluid loss.','HR, MAP, Hgb/bleeding, UOP, mentation','Find and control the loss; reassess response to ordered resuscitation.'],
['Obstructive shock','Shock','Mechanical impairment of cardiac filling or output (e.g., PE, tamponade, tension physiology).','Sudden change, JVD, lung sounds, bedside ultrasound if available','Escalate early; definitive treatment is cause-specific.'],
['ARDS','Respiratory','Inflammatory noncardiogenic pulmonary edema with impaired oxygenation.','SpO2/ABG, P/F ratio, plateau pressure, ventilator synchrony','Lung-protective ventilation and proning decisions are team/protocol driven.'],
['COPD exacerbation','Respiratory','Airflow obstruction with dynamic hyperinflation risk.','Work of breathing, ABG, auto-PEEP, mental status','Allow adequate exhalation; rising pressures can be air trapping.'],
['Pulmonary edema','Respiratory','Fluid in alveoli from cardiogenic or noncardiogenic causes.','Oxygenation, work of breathing, BP, I&O, lung exam','Rapid changes require re-evaluation of cause and ventilation plan.'],
['Pulmonary embolism','Respiratory','Pulmonary vascular obstruction that can strain the right ventricle.','O2 need, HR, BP, signs of RV strain, bleeding risk','Sudden hypotension or syncope signals high risk—escalate promptly.'],
['Acute kidney injury','Renal','Abrupt decline in renal function from perfusion, injury, or obstruction.','UOP, creatinine, potassium, bicarbonate, volume status','Trend rather than a single creatinine; review nephrotoxins and obstruction clues.'],
['DKA / HHS','Endocrine','Hyperglycemic crisis with dehydration; DKA includes ketoacidosis.','Glucose, potassium, anion gap, bicarbonate, neuro status','Use institutional insulin/fluid/electrolyte protocol; potassium drives safety.'],
['GI bleeding','Hematology','Overt or occult blood loss from GI tract.','Hemodynamics, Hgb trend, stool/emesis, coags, access','Massive bleeding is a resuscitation and source-control problem; follow transfusion policy.'],
['DIC','Hematology','Consumptive coagulopathy secondary to an underlying trigger.','Platelets, fibrinogen, PT/INR, bleeding/thrombosis','Treat the trigger; component support follows provider/institutional plan.'],
['Status epilepticus','Neuro','Prolonged or recurrent seizure activity without recovery.','Airway, glucose, temperature, seizure timing, EEG if ordered','Time and document events precisely; airway and medication sequence are protocol-driven.'],
['Increased ICP','Neuro','Elevated intracranial pressure risks reduced cerebral perfusion.','Neuro checks, pupils, BP/MAP, sodium/osmolality if ordered','Avoid delays in new neuro changes; positioning and osmotherapy follow local orders.'],
['Post-cardiac arrest syndrome','Cardiac','Global ischemia-reperfusion injury after ROSC.','Airway/O2/CO2, MAP, rhythm, temperature, glucose, neuro exam','Avoid hyperoxia/hypotension; follow your post-ROSC pathway.']];
const quick=[
['MAP <65 / refractory hypotension','Confirm measurement and rhythm; assess perfusion, volume status, bleeding, sepsis/source control, pump failure, obstruction, and medication effects. Trend lactate/UOP/mentation; escalate early.','Call/escalate for worsening perfusion, rapidly increasing pressor needs, new dysrhythmia, suspected hemorrhage, or concern for obstruction.'],
['Severe metabolic acidosis','Confirm ABG/VBG and chemistry; calculate anion gap; assess lactate, ketones, renal failure, toxins, diarrhea/renal losses. Assess ventilation—bicarbonate can increase CO2 burden.','Escalate severe acidemia, rising lactate, hyperkalemia, declining mental status, or ventilation failure.'],
['Refractory hypoxemia','Check patient first: airway, chest rise, waveform, secretions, tube depth, breath sounds, hemodynamics. Then circuit/ventilator: FiO2 source, disconnection, pressures, PEEP, alarms. Consider edema, ARDS, PE, pneumothorax.','Call immediately for rapidly falling SpO2, unilateral absent sounds, severe distress, instability, or suspected tension physiology.'],
['Post-ROSC','Prioritize airway/ventilation, avoid hypoxemia and hyperoxia, support ordered MAP target, obtain 12-lead/labs, temperature management, and frequent neurologic assessment.','Activate your facility post-arrest pathway; document timing and interventions.'],
['Sudden ventilator deterioration','Use DOPE: Displacement, Obstruction, Pneumothorax, Equipment. Disconnect and bag per emergency protocol if indicated; assess patient and call for help.','A sudden pressure, volume, or oxygenation change is an emergency until assessed.']];
const $=s=>document.querySelector(s), app=$('#app');let tab='home',query='',detail=null;let fav=JSON.parse(localStorage.favs||'[]');const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function header(){return `<header class="top"><div class="brand"><div class="mark">+</div><div><div class="eyebrow">Personal bedside brain</div><div class="title">ICU Pocket Reference</div></div></div><button class="back" onclick="show('favorites')">★ ${fav.length}</button></header>`}function cards(){return `<div class="grid"><button class="card" onclick="show('meds')"><div class="icon">💊</div><strong>Medications</strong><small>${meds.length} quick cards</small></button><button class="card" onclick="show('dx')"><div class="icon">▣</div><strong>Conditions</strong><small>${dx.length} ICU essentials</small></button><button class="card" onclick="show('quick')"><div class="icon">⚡</div><strong>Right now</strong><small>Problem guides</small></button><button class="card" onclick="show('calcs')"><div class="icon">⌁</div><strong>Calculators</strong><small>7 bedside tools</small></button><button class="card" onclick="show('notes')"><div class="icon">✎</div><strong>My protocols</strong><small>Private local notes</small></button></div>`}
function list(items,type){let filtered=items.filter(x=>x.join(' ').toLowerCase().includes(query.toLowerCase()));return `<h2>${type==='med'?'Medications':'Conditions'}</h2><div class="count">${filtered.length} result${filtered.length===1?'':'s'}</div><div class="list">${filtered.map((x,i)=>`<button class="item" onclick="openDetail('${type}',${items.indexOf(x)})"><span class="tag">${esc(x[1])}</span><h3>${esc(x[0])}</h3><small>${esc(x[2])}</small>${fav.includes(type+items.indexOf(x))?'<span class="star">★</span>':''}</button>`).join('')||'<div class="empty">No matching reference found.</div>'}</div>`}
function detailView(type,i){let x=(type==='med'?meds:dx)[i],id=type+i,star=fav.includes(id);return `<button class="back" onclick="show('${type==='med'?'meds':'dx'}')">← Back</button><article class="detail"><div class="detail-head"><div><h1>${esc(x[0])}</h1><div class="tag">${esc(x[1])} · general education</div></div><button class="star" onclick="toggleFav('${id}')">${star?'★':'☆'}</button></div><div class="section"><h3>Overview</h3><p>${esc(x[2])}</p></div><div class="section"><h3>Monitor / trend</h3><p>${esc(x[3])}</p></div><div class="section warn"><h3>ICU pearl</h3><p>${esc(x[4])}</p></div>${noteBox(id,x[0])}</article>`}
function noteBox(id,name){return `<div class="protocol"><label>MY WORKPLACE NOTES — PRIVATE / LOCAL ONLY</label><small>Not a hospital policy. Verify against your current orders, policies, and pharmacy guidance.</small><textarea id="note">${esc(localStorage['note-'+id]||'')}</textarea><button class="save" onclick="saveNote('${id}')">Save notes for ${esc(name)}</button></div>`}
function quickView(){return `<h2>Right now</h2><p class="count">General reference only — use emergency response systems and local protocols.</p><div class="list">${quick.map((x,i)=>`<button class="item" onclick="openDetail('quick',${i})"><span class="tag">Problem guide</span><h3>${x[0]}</h3><small>${x[1]}</small></button>`).join('')}</div>`}function quickDetail(i){let x=quick[i];return `<button class="back" onclick="show('quick')">← Back</button><article class="detail"><h1>${x[0]}</h1><div class="section danger"><h3>Rapid bedside check</h3><p>${x[1]}</p></div><div class="section warn"><h3>Communicate / escalate</h3><p>${x[2]}</p></div>${noteBox('quick'+i,x[0])}</article>`}
const calc=[['MAP','(SBP + 2 × DBP) ÷ 3',[['SBP','sbp'],['DBP','dbp']],v=>((v.sbp+2*v.dbp)/3).toFixed(0)+' mmHg'],['Anion gap','Na − (Cl + HCO₃)',[['Na','na'],['Cl','cl'],['HCO₃','hco3']],v=>(v.na-v.cl-v.hco3).toFixed(1)+' mEq/L'],['Corrected sodium','Na + 1.6 × ((glucose − 100) ÷ 100)',[['Na','na'],['Glucose','glu']],v=>(v.na+1.6*((v.glu-100)/100)).toFixed(1)+' mEq/L'],['Corrected calcium','Ca + 0.8 × (4 − albumin)',[['Calcium','ca'],['Albumin','alb']],v=>(v.ca+.8*(4-v.alb)).toFixed(2)+' mg/dL'],['P/F ratio','PaO₂ ÷ FiO₂ (decimal)',[['PaO₂','pao2'],['FiO₂ %','fio2']],v=>(v.pao2/(v.fio2/100)).toFixed(0)],['QTc (Bazett)','QT ÷ √RR (both in seconds)',[['QT ms','qt'],['HR bpm','hr']],v=>{let rr=60/v.hr;return (v.qt/1000/Math.sqrt(rr)*1000).toFixed(0)+' ms'}],['Shock index','HR ÷ SBP',[['HR','hr'],['SBP','sbp']],v=>(v.hr/v.sbp).toFixed(2)]];
function calcs(){return `<h2>Calculators</h2><p class="count">Check units and interpret with the full clinical picture.</p>${calc.map((c,i)=>`<div class="calc"><h3>${c[0]}</h3><small>${c[1]}</small><div class="fields">${c[2].map(f=>`<label>${f[0]}<input type="number" inputmode="decimal" id="c${i}-${f[1]}" oninput="runCalc(${i})"></label>`).join('')}</div><div class="result" id="r${i}">—</div></div>`).join('')}`}
function notes(){return `<h2>My protocols & notes</h2><div class="protocol"><label>PRIVATE WORKPLACE REFERENCE</label><p>Keep hospital-specific policies, phone numbers, dilution notes, and workflow reminders here. This stays in this browser on this device.</p><textarea id="master-note" placeholder="Example: Sepsis pathway location, rapid response extension, unit-specific titration reminder…">${esc(localStorage.masterNotes||'')}</textarea><button class="save" onclick="localStorage.masterNotes=$('#master-note').value;alert('Saved on this device.')">Save my notes</button></div><div class="section warn"><h3>Safety boundary</h3><p>This app is a personal educational reference, not a prescribing tool or replacement for clinical judgment, orders, current institutional policy, pharmacy guidance, or emergency response procedures.</p></div>`}
function render(){let body=detail?(detail.type==='quick'?quickDetail(detail.i):detailView(detail.type,detail.i)):tab==='home'?`<div class="disclaimer"><strong>General education only.</strong> Use current orders, institution policies, pharmacy guidance, and clinical judgment.</div><div class="search">⌕ <input autofocus placeholder="Search meds, conditions, problems…" value="${esc(query)}" oninput="query=this.value;searchAll()"></div>${query?searchResults():`<h2>Quick access</h2><div class="quick">${quick.slice(0,3).map((x,i)=>`<button class="card" onclick="openDetail('quick',${i})"><div class="tag">Right now</div><strong>${x[0]}</strong></button>`).join('')}</div><h2>Browse</h2>${cards()}`}`:tab==='meds'?list(meds,'med'):tab==='dx'?list(dx,'dx'):tab==='quick'?quickView():tab==='calcs'?calcs():tab==='notes'?notes():favorites();app.innerHTML=header()+body+`<nav class="nav"><div class="nav-inner">${[['home','⌂','Home'],['meds','💊','Meds'],['dx','▣','Conditions'],['calcs','⌁','Tools'],['notes','✎','Notes']].map(n=>`<button class="${tab===n[0]&&!detail?'active':''}" onclick="show('${n[0]}')"><span>${n[1]}</span>${n[2]}</button>`).join('')}</div></nav>`}
function searchResults(){let all=[...meds.map((x,i)=>['med',i,x]),...dx.map((x,i)=>['dx',i,x]),...quick.map((x,i)=>['quick',i,x])].filter(x=>x[2].join(' ').toLowerCase().includes(query.toLowerCase()));return `<h2>Search</h2><div class="list">${all.map(x=>`<button class="item" onclick="openDetail('${x[0]}',${x[1]})"><span class="tag">${x[0]==='med'?'Medication':x[0]==='dx'?'Condition':'Problem guide'}</span><h3>${x[2][0]}</h3><small>${x[2][2]}</small></button>`).join('')||'<div class="empty">No matches.</div>'}</div>`}function favorites(){let all=[...meds.map((x,i)=>['med',i,x]),...dx.map((x,i)=>['dx',i,x])].filter(x=>fav.includes(x[0]+x[1]));return `<h2>Favorites</h2><div class="list">${all.map(x=>`<button class="item" onclick="openDetail('${x[0]}',${x[1]})"><span class="tag">${x[2][1]}</span><h3>${x[2][0]}</h3></button>`).join('')||'<div class="empty">Tap ☆ on any medication or condition to keep it here.</div>'}</div>`}function show(x){tab=x;detail=null;query='';render();scrollTo(0,0)}function openDetail(type,i){detail={type,i};render();scrollTo(0,0)}function toggleFav(id){fav=fav.includes(id)?fav.filter(x=>x!==id):[...fav,id];localStorage.favs=JSON.stringify(fav);render()}function saveNote(id){localStorage['note-'+id]=$('#note').value;alert('Saved on this device.')}function runCalc(i){let c=calc[i],v={};c[2].forEach(f=>v[f[1]]=Number($('#c'+i+'-'+f[1]).value));$('#r'+i).textContent=c[2].every(f=>Number.isFinite(v[f[1]])&&v[f[1]]!==0)?c[3](v):'—'}function searchAll(){render()}if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
const refs=[
['Sepsis & septic shock','Surviving Sepsis Campaign, 2021','https://www.idsociety.org/practice-guideline/surviving-sepsis-campaign-adult-guidelines-2021','Primary guideline for septic-shock content and vasopressor framing.'],
['Cardiac arrest / post-ROSC','American Heart Association: Adult Advanced Life Support','https://cpr.heart.org/en/resuscitation-science/cpr-and-ecc-guidelines/adult-advanced-life-support/','Current AHA guideline hub for adult cardiac arrest and cardiovascular emergencies.'],
['Sedation, analgesia & delirium','SCCM PADIS Guidelines','https://www.sccm.org/clinical-resources/guidelines/guidelines/guidelines-for-the-prevention-and-management-of-pa','Source for general ICU sedation and analgesia concepts.'],
['Acute kidney injury','KDIGO AKI / AKD Guideline hub','https://kdigo.org/guidelines/acute-kidney-injury/','Check current publication status and your local pathway.'],
['Medication details','FDA Drugs@FDA','https://www.accessdata.fda.gov/scripts/cder/daf/','Use current labeling, pharmacy guidance, and local policy for doses and administration.']];
function references(){return `<h2>References</h2><p class="count">Starter sources for this educational build. Check the current guideline and follow local policy where it differs.</p><div class="list">${refs.map(r=>`<a class="item" style="color:var(--text);text-decoration:none" href="${r[2]}" target="_blank" rel="noopener"><span class="tag">${r[0]}</span><h3>${r[1]} ↗</h3><small>${r[3]}</small></a>`).join('')}</div><div class="section warn"><h3>Source scope</h3><p>These sources support the general topics; bedside summaries are not line-by-line evidence mapped. Medication doses, dilutions, compatibility, and titration are intentionally omitted: use your pharmacy and institutional references.</p></div>`}
cards=()=>`<div class="grid"><button class="card" onclick="show('meds')"><div class="icon">M</div><strong>Medications</strong><small>${meds.length} quick cards</small></button><button class="card" onclick="show('dx')"><div class="icon">+</div><strong>Conditions</strong><small>${dx.length} ICU essentials</small></button><button class="card" onclick="show('quick')"><div class="icon">!</div><strong>Right now</strong><small>Problem guides</small></button><button class="card" onclick="show('calcs')"><div class="icon">#</div><strong>Calculators</strong><small>7 bedside tools</small></button><button class="card" onclick="show('notes')"><div class="icon">N</div><strong>My protocols</strong><small>Private local notes</small></button><button class="card" onclick="show('refs')"><div class="icon">R</div><strong>References</strong><small>Guidelines & sources</small></button></div>`;
render=function(){let body=detail?(detail.type==='quick'?quickDetail(detail.i):detailView(detail.type,detail.i)):tab==='home'?`<div class="disclaimer"><strong>General education only.</strong> Use current orders, institution policies, pharmacy guidance, and clinical judgment.</div><div class="search">Search <input autofocus placeholder="Search meds, conditions, problems..." value="${esc(query)}" oninput="query=this.value;searchAll()"></div>${query?searchResults():`<h2>Quick access</h2><div class="quick">${quick.slice(0,3).map((x,i)=>`<button class="card" onclick="openDetail('quick',${i})"><div class="tag">Right now</div><strong>${x[0]}</strong></button>`).join('')}</div><h2>Browse</h2>${cards()}`}`:tab==='meds'?list(meds,'med'):tab==='dx'?list(dx,'dx'):tab==='quick'?quickView():tab==='calcs'?calcs():tab==='notes'?notes():tab==='refs'?references():favorites();app.innerHTML=header()+body+`<nav class="nav"><div class="nav-inner">${[['home','Home'],['meds','Meds'],['dx','Conditions'],['calcs','Tools'],['notes','Notes']].map(n=>`<button class="${tab===n[0]&&!detail?'active':''}" onclick="show('${n[0]}')">${n[1]}</button>`).join('')}</div></nav>`};render();
